server:
    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    num-threads: 32
    so-reuseport: yes
    so-sndbuf: 8m
    so-rcvbuf: 8m
    access-control: 0.0.0.0/0 allow_snoop
    
    verbosity: 1          # Maximize log output, observe all details
    use-syslog: no        # Output directly to terminal, convenient for real-time viewing
    log-queries: yes    # Ensure queries are logged
    qname-minimisation: no
    harden-glue: no                 # (default yes) Do not verify the correctness of glue records
    harden-dnssec-stripped: no      # (default yes) Do not check whether DNSSEC data has been maliciously stripped
    harden-below-nxdomain: no       # (default yes) Do not defend against NXDOMAIN attacks
    harden-referral-path: no        # (default no, but better to explicitly disable) Do not check the legitimacy of the query path
    harden-algo-downgrade: no       # (default no) Allow algorithm downgrade attacks
    # infra-cache-numhosts: 0
    infra-host-ttl: 0
    infra-keep-probing: yes
    max-sent-count: 1024

    auto-trust-anchor-file: ""  # Clear the auto trust anchor
    trust-anchor-file: ""       # Clear the manual trust anchor
    val-clean-additional: no        

    msg-cache-size: 0
    rrset-cache-size: 0
    neg-cache-size: 0
    cache-max-negative-ttl: 0
    unwanted-reply-threshold: 0     # Do not reject any "unwanted" responses
    jostle-timeout: 3600000
    num-queries-per-thread: 5096
    target-fetch-policy: "-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1"

    msg-cache-slabs: 32
    rrset-cache-slabs: 32
    infra-cache-slabs: 32
    key-cache-slabs: 32

    # new weak conf
    outgoing-range: 8192
    outbound-msg-retry: 20