server:
    num-threads: 1
    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    # Other settings
    # Allow access only from the local network
    access-control: 10.0.0.0/8 allow_snoop
    # Adjust the verbosity of the log
    verbosity: 4
    use-syslog: no        # Output directly to terminal for real-time viewing
    log-queries: yes    # Ensure queries are logged
    qname-minimisation: no
    harden-glue: no                 # (default yes) Do not validate correctness of glue records
    harden-dnssec-stripped: no      # (default yes) Do not check if DNSSEC data is maliciously stripped
    harden-below-nxdomain: no       # (default yes) Do not defend against NXDOMAIN attacks
    harden-referral-path: no        # (default no) Do not check validity of query path
    harden-algo-downgrade: no       # (default no) Allow algorithm downgrade attacks

    auto-trust-anchor-file: ""  # Clear auto trust anchor
    trust-anchor-file: ""       # Clear manual trust anchor
    val-clean-additional: no

    unwanted-reply-threshold: 0     # Do not reject any "unwanted" responses

    msg-cache-slabs: 4
    rrset-cache-slabs: 4
    infra-cache-slabs: 4
    key-cache-slabs: 4