import json
import glob
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import PercentFormatter
from pathlib import Path

sns.set_theme(style="whitegrid")
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = ['DejaVu Sans', 'sans-serif']

def load_cache_data(data_dir):
    """
    Load data and extract Cache-related diff information.
    """
    cache_records = []

    files = glob.glob(os.path.join(data_dir, "analyze_*.json")) # Assumes files still use this naming pattern, or change to *.json
    print(f"Found {len(files)} files. Loading Cache Data...")

    for file_path in files:
        try:
            filename = Path(file_path).stem
            iteration_id = filename.split('_')[1] if '_' in filename else filename

            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read().strip()
                if not content: continue
                data = json.loads(content)

            for key, result in data.items():
                if not key.startswith("cache:"):
                    continue

                resolver_name = key.replace("cache:", "")
                if result.get("status") != "success":
                    continue

                diff = result.get("diff") or {}
                summary = diff.get("summary") or {}

                # Basic counts
                added_cnt = summary.get("added", 0)
                modified_cnt = summary.get("modified", 0)
                removed_cnt = summary.get("removed", 0)

                # Derived metrics
                total_churn = added_cnt + modified_cnt + removed_cnt
                net_growth = added_cnt - removed_cnt
                modify_ratio = modified_cnt / total_churn if total_churn > 0 else 0

                # Deep analysis of Added records
                rtypes_added = {}
                max_ttl = 0
                for record in diff.get("added", []):
                    rtype = record.get("rtype", "UNKNOWN")
                    rtypes_added[rtype] = rtypes_added.get(rtype, 0) + 1
                    max_ttl = max(max_ttl, record.get("original_ttl", 0))

                # Deep analysis of Modified records
                rtypes_modified = {}
                for record in diff.get("modified", []):
                    rtype = record.get("rtype", "UNKNOWN")
                    rtypes_modified[rtype] = rtypes_modified.get(rtype, 0) + 1

                # Build flattened data row
                row = {
                    "iteration": iteration_id,
                    "resolver": resolver_name,
                    "added": added_cnt,
                    "modified": modified_cnt,
                    "removed": removed_cnt,
                    "total_churn": total_churn,
                    "net_growth": net_growth,
                    "modify_ratio": modify_ratio,
                    "max_ttl": max_ttl
                }
                # Add RTYPE distribution as columns (e.g., column names RTYPE_A, RTYPE_AAAA)
                for rt, cnt in rtypes_added.items():
                    row[f"RTYPE_ADDED_{rt}"] = cnt

                # Add Modified RTYPE distribution as columns
                for rt, cnt in rtypes_modified.items():
                    row[f"RTYPE_MODIFIED_{rt}"] = cnt

                cache_records.append(row)

        except Exception as e:
            print(f"Warning: Error processing {file_path}: {str(e)}")

    df = pd.DataFrame(cache_records)
    # Fill NaN values generated by RTYPE columns
    df = df.fillna(0)
    return df

def viz_1_cache_churn_stack(df_cache, output_dir):
    """1. Cache Activity Composition (Added / Modified / Removed) Stacked Chart"""
    if df_cache.empty: return

    # Calculate average add/delete/modify counts per resolver
    stats = df_cache.groupby('resolver')[['added', 'modified', 'removed']].mean()

    ax = stats.plot(kind='bar', stacked=True, figsize=(10, 6), color=['#2ecc71', '#f1c40f', '#e74c3c'])

    # Remove title
    # plt.title('Average Cache Churn per Query')
    plt.ylabel('Number of Records')
    plt.xlabel('Resolver')
    # Place x-axis labels horizontally
    plt.xticks(rotation=0)
    # Remove grid
    ax.grid(False)
    # Remove top and right borders
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    plt.legend(['Added', 'Modified', 'Removed'], title="Action")

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_1_churn_stack.pdf'), format='pdf', dpi=300)
    plt.close()

def viz_2_net_growth_and_modify_ratio(df_cache, output_dir):
    """2. Net Cache Growth (bars) vs Refresh Ratio (line) dual-axis chart"""
    if df_cache.empty: return

    stats = df_cache.groupby('resolver')[['net_growth', 'modify_ratio']].mean().reset_index()

    fig, ax1 = plt.subplots(figsize=(10, 6))

    # Left axis: net growth
    sns.barplot(data=stats, x='resolver', y='net_growth', ax=ax1, color='#3498db', alpha=0.7)
    ax1.set_ylabel('Avg Net Cache Growth')
    ax1.set_xlabel('Resolver')

    # Right axis: refresh ratio
    ax2 = ax1.twinx()
    sns.pointplot(data=stats, x='resolver', y='modify_ratio', ax=ax2, color='#e67e22', markers='D')
    ax2.set_ylabel('Avg Modify Ratio')
    ax2.set_ylim(0, max(stats['modify_ratio'].max() * 1.2, 0.1)) # Leave space at the top

    ax2.yaxis.set_major_formatter(PercentFormatter(1.0))

    plt.title('Net Growth vs Freshening Aggressiveness')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_2_growth_and_refresh.png'), dpi=300)
    plt.close()

def viz_3_added_rtype_distribution(df_cache, output_dir):
    """3. Added Cache RTYPE Distribution Comparison"""
    if df_cache.empty: return

    # Filter all columns starting with RTYPE_ADDED_
    rtype_cols = [col for col in df_cache.columns if col.startswith("RTYPE_ADDED_")]
    if not rtype_cols: return

    # Calculate average of each RTYPE
    stats = df_cache.groupby('resolver')[rtype_cols].mean()

    # Convert to percentages for chart aesthetics
    stats_pct = stats.div(stats.sum(axis=1), axis=0)

    # Clean column names RTYPE_ADDED_A -> A
    stats_pct.columns = [c.replace("RTYPE_ADDED_", "") for c in stats_pct.columns]

    ax = stats_pct.plot(kind='bar', stacked=True, figsize=(12, 7), colormap='tab20')

    plt.title('Added Cache RTYPE Distribution')
    plt.ylabel('Ratio')
    plt.xlabel('Resolver')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title="Record Type")

    # Annotate blocks larger than 5%
    for c in ax.containers:
        labels = [f'{v.get_height():.1%}' if v.get_height() > 0.05 else '' for v in c]
        ax.bar_label(c, labels=labels, label_type='center', fontsize=8, color='white')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_3_rtype_dist.png'), dpi=300)
    plt.close()

def viz_4_modified_rtype_distribution(df_cache, output_dir):
    """4. Modified/Refreshed Cache RTYPE Distribution Comparison"""
    if df_cache.empty: return

    # Filter all columns starting with RTYPE_MODIFIED_
    rtype_cols = [col for col in df_cache.columns if col.startswith("RTYPE_MODIFIED_")]
    if not rtype_cols: return

    # Calculate average of each RTYPE
    stats = df_cache.groupby('resolver')[rtype_cols].mean()

    # Convert to percentages for chart aesthetics
    stats_pct = stats.div(stats.sum(axis=1), axis=0)

    # Clean column names RTYPE_MODIFIED_A -> A
    stats_pct.columns = [c.replace("RTYPE_MODIFIED_", "") for c in stats_pct.columns]

    ax = stats_pct.plot(kind='bar', stacked=True, figsize=(12, 7), colormap='Set2')

    plt.title('Modified Cache RTYPE Distribution')
    plt.ylabel('Ratio')
    plt.xlabel('Resolver')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title="Record Type")

    # Annotate blocks larger than 5%
    for c in ax.containers:
        labels = [f'{v.get_height():.1%}' if v.get_height() > 0.05 else '' for v in c]
        ax.bar_label(c, labels=labels, label_type='center', fontsize=8, color='white')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_4_modified_rtype_dist.png'), dpi=300)
    plt.close()

def viz_5_max_ttl_observed(df_cache, output_dir):
    """5. Observed Maximum Allowed TTL (Upper Bound Truncation Strategy)"""
    if df_cache.empty: return

    # Since we're looking for the policy upper bound, take the maximum value observed across all tests for this resolver
    stats = df_cache.groupby('resolver')['max_ttl'].max().reset_index()

    plt.figure(figsize=(10, 6))
    sns.barplot(data=stats, x='resolver', y='max_ttl', color='#9b59b6')

    plt.title('Observed Maximum TTL (Seconds)')
    plt.ylabel('Max TTL')
    plt.xlabel('Resolver')

    # Add horizontal reference lines (common TTLs, e.g., 24 hours, 48 hours, 6 days)
    plt.axhline(86400, color='r', linestyle='--', alpha=0.5, label='1 Day (86400s)')
    plt.axhline(172800, color='b', linestyle='--', alpha=0.5, label='2 Days (172800s)')
    plt.axhline(518400, color='g', linestyle='--', alpha=0.5, label='6 Days (Root NS)')

    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_5_max_ttl.png'), dpi=300)
    plt.close()

def parse_dns_flags(flags):
    """Parse DNS flags bits"""
    return {
        'QR': (flags >> 15) & 1,
        'OPCODE': (flags >> 11) & 0xF,
        'AA': (flags >> 10) & 1,  # Authoritative Answer
        'TC': (flags >> 9) & 1,
        'RD': (flags >> 8) & 1,
        'RA': (flags >> 7) & 1,
        'AD': (flags >> 5) & 1,  # Authentic Data (DNSSEC)
        'CD': (flags >> 4) & 1,
        'RCODE': flags & 0xF
    }

def load_cache_policy_data(data_dir):
    """
    Load cache policy related data: trigger info, flags, authorities/additionals processing, etc.
    """
    policy_records = []

    files = glob.glob(os.path.join(data_dir, "analyze_*.json"))
    print(f"Found {len(files)} files. Loading Cache Policy Data...")

    for file_path in files:
        try:
            filename = Path(file_path).stem
            iteration_id = filename.split('_')[1] if '_' in filename else filename

            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read().strip()
                if not content: continue
                data = json.loads(content)

            for key, result in data.items():
                if not key.startswith("cache:"):
                    continue

                resolver_name = key.replace("cache:", "")
                if result.get("status") != "success":
                    continue

                diff = result.get("diff") or {}
                trigger = diff.get("trigger") or {}

                if not trigger:
                    continue

                # Parse flags
                flags = trigger.get("flags", 0)
                parsed_flags = parse_dns_flags(flags)

                # Records in trigger
                answers = trigger.get("answers", [])
                authorities = trigger.get("authorities", [])
                additionals = trigger.get("additionals", [])
                non_opt_additionals = [a for a in additionals if a.get("type") != "OPT"]

                # Records in cache
                added = diff.get("added", [])
                modified = diff.get("modified", [])

                # Count negative cache
                neg_count = sum(1 for r in added if r.get("is_neg"))

                # Count rtypes in trigger
                trigger_rtypes = {}
                for r in answers + authorities + non_opt_additionals:
                    rtype = r.get("type", "UNKNOWN")
                    trigger_rtypes[rtype] = trigger_rtypes.get(rtype, 0) + 1

                # Count rtypes in added
                added_rtypes = {}
                for r in added:
                    rtype = r.get("rtype", "UNKNOWN")
                    added_rtypes[rtype] = added_rtypes.get(rtype, 0) + 1

                # Count rtypes and modification types in modified
                modified_rtypes = {}
                ttl_changes = 0
                rdata_changes = 0
                for m in modified:
                    old = m.get("old", {})
                    new = m.get("new", {})
                    rtype = old.get("rtype", "UNKNOWN")
                    modified_rtypes[rtype] = modified_rtypes.get(rtype, 0) + 1

                    if old.get("ttl") != new.get("ttl"):
                        ttl_changes += 1
                    if old.get("rdata") != new.get("rdata"):
                        rdata_changes += 1

                # Build record
                row = {
                    "iteration": iteration_id,
                    "resolver": resolver_name,
                    "flags_aa": parsed_flags["AA"],
                    "flags_ad": parsed_flags["AD"],
                    "flags_rcode": parsed_flags["RCODE"],
                    "trigger_answers": len(answers),
                    "trigger_authorities": len(authorities),
                    "trigger_additionals": len(non_opt_additionals),
                    "cached_added": len(added),
                    "cached_modified": len(modified),
                    "neg_cache_count": neg_count,
                    "ttl_changes": ttl_changes,
                    "rdata_changes": rdata_changes,
                }

                # Add rtype statistics
                for rt, cnt in trigger_rtypes.items():
                    row[f"TRIGGER_RTYPE_{rt}"] = cnt
                for rt, cnt in added_rtypes.items():
                    row[f"CACHED_RTYPE_{rt}"] = cnt
                for rt, cnt in modified_rtypes.items():
                    row[f"MODIFIED_RTYPE_{rt}"] = cnt

                policy_records.append(row)

        except Exception as e:
            print(f"Warning: Error processing {file_path}: {str(e)}")

    df = pd.DataFrame(policy_records)
    df = df.fillna(0)
    return df

def load_modified_detail_data(data_dir):
    """
    Load detailed data of modified records for TTL refresh strategy analysis
    """
    modified_records = []

    files = glob.glob(os.path.join(data_dir, "analyze_*.json"))

    for file_path in files:
        try:
            filename = Path(file_path).stem
            iteration_id = filename.split('_')[1] if '_' in filename else filename

            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read().strip()
                if not content: continue
                data = json.loads(content)

            for key, result in data.items():
                if not key.startswith("cache:"):
                    continue

                resolver_name = key.replace("cache:", "")
                if result.get("status") != "success":
                    continue

                diff = result.get("diff") or {}
                modified = diff.get("modified", [])

                for m in modified:
                    old = m.get("old", {})
                    new = m.get("new", {})

                    # Calculate TTL change
                    old_ttl = old.get("ttl", 0)
                    new_ttl = new.get("ttl", 0)
                    ideal = m.get("ideal", 0)
                    actual = m.get("actual", 0)

                    # TTL refresh deviation
                    if ideal and ideal > 0:
                        ttl_deviation = actual - ideal
                        ttl_deviation_ratio = ttl_deviation / ideal
                    else:
                        ttl_deviation = 0
                        ttl_deviation_ratio = 0

                    row = {
                        "iteration": iteration_id,
                        "resolver": resolver_name,
                        "rtype": old.get("rtype", "UNKNOWN"),
                        "name": old.get("name", ""),
                        "old_ttl": old_ttl,
                        "new_ttl": new_ttl,
                        "ideal_ttl": ideal,
                        "actual_ttl": actual,
                        "ttl_deviation": ttl_deviation,
                        "ttl_deviation_ratio": ttl_deviation_ratio,
                        "is_neg": old.get("is_neg", False),
                        "rdata_changed": old.get("rdata") != new.get("rdata"),
                    }
                    modified_records.append(row)

        except Exception as e:
            pass

    df = pd.DataFrame(modified_records)
    return df

def viz_6_negative_cache_comparison(df_policy, output_dir):
    """6. Negative Cache Strategy Comparison"""
    if df_policy.empty: return

    stats = df_policy.groupby('resolver')['neg_cache_count'].agg(['mean', 'sum', 'max']).reset_index()
    stats.columns = ['resolver', 'avg_neg', 'total_neg', 'max_neg']

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Left chart: average negative cache
    sns.barplot(data=stats, x='resolver', y='avg_neg', ax=axes[0], color='#e74c3c', alpha=0.7)
    axes[0].set_title('Avg Negative Cache Entries')
    axes[0].set_ylabel('Avg Entries')
    axes[0].set_xlabel('Resolver')

    # Right chart: total negative cache
    sns.barplot(data=stats, x='resolver', y='total_neg', ax=axes[1], color='#c0392b', alpha=0.7)
    axes[1].set_title('Total Negative Cache Entries')
    axes[1].set_ylabel('Total Entries')
    axes[1].set_xlabel('Resolver')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_6_negative_cache.png'), dpi=300)
    plt.close()

def viz_7_trigger_vs_cached_records(df_policy, output_dir):
    """7. Trigger Records vs Cached Records Comparison"""
    if df_policy.empty: return

    stats = df_policy.groupby('resolver').agg({
        'trigger_answers': 'mean',
        'trigger_authorities': 'mean',
        'cached_added': 'mean'
    }).reset_index()

    fig, ax = plt.subplots(figsize=(10, 6))

    x = range(len(stats['resolver']))
    width = 0.25

    bars1 = ax.bar([i - width for i in x], stats['trigger_answers'], width,
                   label='Trigger Answers', color='#3498db')
    bars2 = ax.bar(x, stats['trigger_authorities'], width,
                   label='Trigger Authorities', color='#e67e22')
    bars3 = ax.bar([i + width for i in x], stats['cached_added'], width,
                   label='Cached Added', color='#2ecc71')

    ax.set_xlabel('Resolver')
    ax.set_ylabel('Avg Record Count')
    ax.set_title('Trigger Records vs Cached Records')
    ax.set_xticks(x)
    ax.set_xticklabels(stats['resolver'])
    ax.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_7_trigger_vs_cached.png'), dpi=300)
    plt.close()

def viz_8_modification_type_breakdown(df_policy, output_dir):
    """8. Modified Record Modification Type Analysis"""
    if df_policy.empty: return

    stats = df_policy.groupby('resolver').agg({
        'ttl_changes': 'sum',
        'rdata_changes': 'sum',
        'cached_modified': 'sum'
    }).reset_index()

    fig, ax = plt.subplots(figsize=(10, 6))

    x = range(len(stats['resolver']))
    width = 0.35

    bars1 = ax.bar([i - width/2 for i in x], stats['ttl_changes'], width,
                   label='TTL Changes', color='#9b59b6')
    bars2 = ax.bar([i + width/2 for i in x], stats['rdata_changes'], width,
                   label='RDATA Changes', color='#1abc9c')

    ax.set_xlabel('Resolver')
    ax.set_ylabel('Total Modifications')
    ax.set_title('Modification Type Distribution')
    ax.set_xticks(x)
    ax.set_xticklabels(stats['resolver'])
    ax.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_8_modification_types.png'), dpi=300)
    plt.close()

def viz_9_ttl_refresh_deviation(df_modified, output_dir):
    """9. TTL Refresh Deviation Analysis"""
    if df_modified.empty: return

    # Filter valid data
    valid_df = df_modified[df_modified['ideal_ttl'] > 0].copy()
    if valid_df.empty: return

    # Calculate TTL deviation by resolver
    stats = valid_df.groupby('resolver').agg({
        'ttl_deviation': ['mean', 'std', 'min', 'max'],
        'ttl_deviation_ratio': ['mean', 'std']
    }).reset_index()
    stats.columns = ['resolver', 'avg_dev', 'std_dev', 'min_dev', 'max_dev',
                     'avg_ratio', 'std_ratio']

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Left chart: absolute deviation
    sns.barplot(data=stats, x='resolver', y='avg_dev', ax=axes[0],
               color='#e74c3c', alpha=0.7)
    axes[0].errorbar(range(len(stats)), stats['avg_dev'],
                    yerr=stats['std_dev'], fmt='k_', capsize=5)
    axes[0].set_title('Avg TTL Refresh Deviation (sec)')
    axes[0].set_ylabel('Deviation (sec)')
    axes[0].set_xlabel('Resolver')

    # Right chart: relative deviation ratio
    sns.barplot(data=stats, x='resolver', y='avg_ratio', ax=axes[1],
               color='#f39c12', alpha=0.7)
    axes[1].errorbar(range(len(stats)), stats['avg_ratio'],
                    yerr=stats['std_ratio'], fmt='k_', capsize=5)
    axes[1].set_title('Avg TTL Refresh Deviation Ratio')
    axes[1].set_ylabel('Deviation Ratio')
    axes[1].set_xlabel('Resolver')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_9_ttl_deviation.png'), dpi=300)
    plt.close()

def viz_10_resolver_comparison_summary(df_policy, output_dir):
    """10. Resolver Cache Policy Comprehensive Comparison"""
    if df_policy.empty: return

    # Comprehensive statistics
    stats = df_policy.groupby('resolver').agg({
        'cached_added': 'mean',
        'cached_modified': 'mean',
        'neg_cache_count': 'mean',
        'ttl_changes': 'sum',
    }).reset_index()

    # Create heatmap-style data
    metrics = ['cached_added', 'cached_modified', 'neg_cache_count', 'ttl_changes']
    stats_normalized = stats.copy()
    for m in metrics:
        max_val = stats[m].max()
        if max_val > 0:
            stats_normalized[m] = stats[m] / max_val

    fig, ax = plt.subplots(figsize=(10, 6))

    # Plot grouped bar chart
    data_for_plot = stats_normalized.set_index('resolver')[metrics]

    # Rename columns
    data_for_plot.columns = [
        'Avg Added',
        'Avg Modified',
        'Avg Neg Cache',
        'Total TTL Chg'
    ]

    sns.heatmap(data_for_plot, annot=True, fmt='.2f', cmap='YlOrRd',
               ax=ax, linewidths=0.5)

    ax.set_title('Resolver Cache Policy Comparison (Normalized)')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_10_policy_summary.png'), dpi=300)
    plt.close()

def load_resolver_path_data(data_dir):
    """
    Load detailed data from resolver's analyzed_path, analyze the association between response records and cache
    """
    path_records = []

    files = glob.glob(os.path.join(data_dir, "analyze_*.json"))
    print(f"Found {len(files)} files. Loading Resolver Path Data...")

    for file_path in files:
        try:
            filename = Path(file_path).stem
            iteration_id = filename.split('_')[1] if '_' in filename else filename

            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read().strip()
                if not content: continue
                data = json.loads(content)

            # Get cache data for association
            cache_data = {}
            for key in data:
                if key.startswith("cache:"):
                    resolver = key.replace("cache:", "")
                    cache_data[resolver] = data[key].get('diff', {})

            # Analyze resolver data
            for key in data:
                if key.startswith("resolver:"):
                    resolver_name = key.replace("resolver:", "")
                    transaction = data[key].get('transaction', {})
                    path = transaction.get('analyzed_path', {})
                    steps = path.get('steps', [])

                    # Get corresponding cache data
                    cache_diff = cache_data.get(resolver_name, {})
                    added_records = cache_diff.get('added', [])
                    modified_records = cache_diff.get('modified', [])

                    # Create cache record index (name + rtype)
                    # added: newly added cache records
                    added_index = {(r.get('name'), r.get('rtype')) for r in added_records}
                    # modified.old: original records that were modified (used to determine if modified)
                    modified_old_index = {(r.get('name'), r.get('rtype')) for r in modified_records}
                    # modified.new: modified records (also part of current cache state)
                    modified_new_index = {(m.get('new', {}).get('name'), m.get('new', {}).get('rtype')) for m in modified_records}

                    # Combined cache index: added + modified.new are both current cache state
                    cached_index = added_index | modified_new_index

                    for step_idx, step in enumerate(steps):
                        resp = step.get('response', {})
                        if not resp:
                            continue

                        flags = resp.get('flags', 0)
                        parsed_flags = parse_dns_flags(flags)

                        answers = resp.get('answers', [])
                        authorities = resp.get('authorities', [])
                        additionals = resp.get('additionals', [])
                        non_opt_additionals = [a for a in additionals if a.get('type') != 'OPT']

                        # Count records by category
                        for record_type, records in [
                            ('answer', answers),
                            ('authority', authorities),
                            ('additional', non_opt_additionals)
                        ]:
                            for rec in records:
                                name = rec.get('name', '')
                                rtype = rec.get('type', 'UNKNOWN')
                                ttl = rec.get('ttl', 0)

                                # Cache status: in added or modified.new
                                is_cached = (name, rtype) in cached_index
                                # Specific cache type
                                is_cached_added = (name, rtype) in added_index
                                is_cached_modified = (name, rtype) in modified_old_index

                                row = {
                                    "iteration": iteration_id,
                                    "resolver": resolver_name,
                                    "step_idx": step_idx,
                                    "record_type": record_type,
                                    "name": name,
                                    "rtype": rtype,
                                    "ttl": ttl,
                                    "flags_aa": parsed_flags['AA'],
                                    "flags_ad": parsed_flags['AD'],
                                    "flags_rcode": parsed_flags['RCODE'],
                                    "is_cached": is_cached,
                                    "is_cached_added": is_cached_added,
                                    "is_cached_modified": is_cached_modified,
                                }
                                path_records.append(row)

        except Exception as e:
            pass

    df = pd.DataFrame(path_records)
    return df

def viz_11_response_record_cache_rate(df_path, output_dir):
    """11. Response Record Cache Rate Comparison (Answers/Authorities/Additionals)"""
    if df_path.empty: return

    # Calculate cache rate by resolver and record_type
    # is_cached = is_cached_added OR is_cached_modified (in added or modified.new)
    stats = df_path.groupby(['resolver', 'record_type']).agg({
        'is_cached': ['sum', 'count'],
    }).reset_index()
    stats.columns = ['resolver', 'record_type', 'cached_count', 'total_count']
    stats['cache_rate'] = stats['cached_count'] / stats['total_count']

    fig, ax = plt.subplots(figsize=(12, 6))

    record_types = ['answer', 'authority', 'additional']
    colors = ['#3498db', '#e67e22', '#9b59b6']
    x = range(len(stats['resolver'].unique()))
    width = 0.25

    for i, (rt, color) in enumerate(zip(record_types, colors)):
        rt_stats = stats[stats['record_type'] == rt]
        ax.bar([xi + i * width - width for xi in x],
               rt_stats['cache_rate'].values,
               width, label=rt.capitalize(), color=color, alpha=0.7)

    ax.set_xlabel('Resolver')
    ax.set_ylabel('Cache Rate')
    ax.set_title('Response Record Cache Rate Comparison')
    ax.set_xticks(x)
    ax.set_xticklabels(stats['resolver'].unique())
    ax.legend()

    # Add percentage labels
    ax.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax.set_ylim(0, 1)

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_11_response_cache_rate.png'), dpi=300)
    plt.close()

def viz_12_aa_ad_cache_rate(df_path, output_dir):
    """12. AA/AD-flagged Record Cache Rate"""
    if df_path.empty: return

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # AA-flagged record cache rate
    aa_records = df_path[df_path['flags_aa'] == 1]
    if not aa_records.empty:
        aa_stats = aa_records.groupby('resolver').agg({
            'is_cached': ['sum', 'count']
        }).reset_index()
        aa_stats.columns = ['resolver', 'cached', 'total']
        aa_stats['rate'] = aa_stats['cached'] / aa_stats['total']

        sns.barplot(data=aa_stats, x='resolver', y='rate', ax=axes[0],
                   color='#2ecc71', alpha=0.7)
        axes[0].set_title('AA-flagged Record Cache Rate')
        axes[0].set_ylabel('Cache Rate')
        axes[0].set_xlabel('Resolver')
        axes[0].yaxis.set_major_formatter(PercentFormatter(1.0))

        # Add value labels
        for i, row in aa_stats.iterrows():
            axes[0].text(i, row['rate'] + 0.02, f'{row["rate"]:.1%}',
                        ha='center', va='bottom', fontsize=9)

    # AD-flagged record cache rate
    ad_records = df_path[df_path['flags_ad'] == 1]
    if not ad_records.empty:
        ad_stats = ad_records.groupby('resolver').agg({
            'is_cached': ['sum', 'count']
        }).reset_index()
        ad_stats.columns = ['resolver', 'cached', 'total']
        ad_stats['rate'] = ad_stats['cached'] / ad_stats['total']

        sns.barplot(data=ad_stats, x='resolver', y='rate', ax=axes[1],
                   color='#f39c12', alpha=0.7)
        axes[1].set_title('AD-flagged Record Cache Rate')
        axes[1].set_ylabel('Cache Rate')
        axes[1].set_xlabel('Resolver')
        axes[1].yaxis.set_major_formatter(PercentFormatter(1.0))

        for i, row in ad_stats.iterrows():
            axes[1].text(i, row['rate'] + 0.02, f'{row["rate"]:.1%}',
                        ha='center', va='bottom', fontsize=9)

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_12_aa_ad_cache_rate.png'), dpi=300)
    plt.close()

def viz_13_rtype_cache_rate_by_section(df_path, output_dir):
    """13. Cache Trigger Rate by RTYPE in Each Section"""
    if df_path.empty: return

    # Filter main rtypes
    main_rtypes = ['A', 'AAAA', 'NS', 'SOA', 'CNAME']

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    for idx, (section, title) in enumerate([
        ('answer', 'Answers'),
        ('authority', 'Authorities'),
        ('additional', 'Additionals')
    ]):
        section_df = df_path[df_path['record_type'] == section]
        if section_df.empty:
            axes[idx].text(0.5, 0.5, 'No Data', ha='center', va='center')
            continue

        # Calculate cache trigger rate by rtype
        rtype_stats = section_df.groupby(['resolver', 'rtype']).agg({
            'is_cached': ['sum', 'count']
        }).reset_index()
        rtype_stats.columns = ['resolver', 'rtype', 'cached', 'total']
        rtype_stats['rate'] = rtype_stats['cached'] / rtype_stats['total']

        # Show only main rtypes
        rtype_stats = rtype_stats[rtype_stats['rtype'].isin(main_rtypes)]

        if not rtype_stats.empty:
            sns.barplot(data=rtype_stats, x='rtype', y='rate', hue='resolver',
                       ax=axes[idx], alpha=0.7)
            axes[idx].set_title(title)
            axes[idx].set_ylabel('Cache Trigger Rate')
            axes[idx].set_xlabel('Record Type')
            axes[idx].yaxis.set_major_formatter(PercentFormatter(1.0))
            axes[idx].legend(loc='upper right', fontsize=8)

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_13_rtype_by_section.png'), dpi=300)
    plt.close()

def viz_14_resolver_policy_heatmap(df_path, output_dir):
    """14. Resolver Cache Policy Comprehensive Heatmap"""
    if df_path.empty: return

    # Calculate various metrics
    metrics = []

    for resolver in df_path['resolver'].unique():
        res_df = df_path[df_path['resolver'] == resolver]

        # Answers cache trigger rate
        answers = res_df[res_df['record_type'] == 'answer']
        answers_rate = answers['is_cached'].mean() if not answers.empty else 0

        # Authorities cache trigger rate
        authorities = res_df[res_df['record_type'] == 'authority']
        authorities_rate = authorities['is_cached'].mean() if not authorities.empty else 0

        # Additionals cache trigger rate
        additionals = res_df[res_df['record_type'] == 'additional']
        additionals_rate = additionals['is_cached'].mean() if not additionals.empty else 0

        # AA cache trigger rate
        aa_records = res_df[res_df['flags_aa'] == 1]
        aa_rate = aa_records['is_cached'].mean() if not aa_records.empty else 0

        # AD cache trigger rate
        ad_records = res_df[res_df['flags_ad'] == 1]
        ad_rate = ad_records['is_cached'].mean() if not ad_records.empty else 0

        metrics.append({
            'resolver': resolver,
            'answers_rate': answers_rate,
            'authorities_rate': authorities_rate,
            'additionals_rate': additionals_rate,
            'aa_rate': aa_rate,
            'ad_rate': ad_rate
        })

    metrics_df = pd.DataFrame(metrics)
    metrics_df = metrics_df.set_index('resolver')

    # Rename columns
    metrics_df.columns = [
        'Answers Trigger',
        'Authorities Trigger',
        'Additionals Trigger',
        'AA Trigger',
        'AD Trigger'
    ]

    fig, ax = plt.subplots(figsize=(10, 6))
    sns.heatmap(metrics_df, annot=True, fmt='.2%', cmap='RdYlGn',
               ax=ax, linewidths=0.5, vmin=0, vmax=1)

    ax.set_title('Resolver Cache Policy Comparison')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_14_policy_heatmap.png'), dpi=300)
    plt.close()

def viz_15_aa_ad_response_stats(df_path, output_dir):
    """15. AA/AD Response Statistics"""
    if df_path.empty: return

    # Count AA/AD responses per resolver
    # Count each step only once (not per record)
    step_stats = df_path.groupby(['resolver', 'iteration', 'step_idx']).agg({
        'flags_aa': 'max',  # All records in the same step have identical flags
        'flags_ad': 'max'
    }).reset_index()

    # Count AA/AD response quantity
    resp_stats = step_stats.groupby('resolver').agg({
        'flags_aa': 'sum',
        'flags_ad': 'sum',
        'step_idx': 'count'  # Total response count
    }).reset_index()
    resp_stats.columns = ['resolver', 'aa_responses', 'ad_responses', 'total_responses']

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # AA Response ratio
    resp_stats['aa_ratio'] = resp_stats['aa_responses'] / resp_stats['total_responses']
    sns.barplot(data=resp_stats, x='resolver', y='aa_ratio', ax=axes[0],
               color='#27ae60', alpha=0.7)
    axes[0].set_title('AA Response Ratio')
    axes[0].set_ylabel('Ratio')
    axes[0].set_xlabel('Resolver')
    axes[0].yaxis.set_major_formatter(PercentFormatter(1.0))

    # AD Response ratio
    resp_stats['ad_ratio'] = resp_stats['ad_responses'] / resp_stats['total_responses']
    sns.barplot(data=resp_stats, x='resolver', y='ad_ratio', ax=axes[1],
               color='#e74c3c', alpha=0.7)
    axes[1].set_title('AD Response Ratio')
    axes[1].set_ylabel('Ratio')
    axes[1].set_xlabel('Resolver')
    axes[1].yaxis.set_major_formatter(PercentFormatter(1.0))

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'cache_15_aa_ad_response_stats.png'), dpi=300)
    plt.close()

if __name__ == "__main__":
    # Please ensure the path matches your actual JSON storage location
    DATA_DIR = "./fuzzer_output/analyze"
    OUTPUT_DIR = "./visualizations"

    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    print("Step 1: Loading cache tracking data...")
    df_cache = load_cache_data(DATA_DIR)

    print("Step 2: Loading cache policy data...")
    df_policy = load_cache_policy_data(DATA_DIR)

    print("Step 3: Loading modified detail data...")
    df_modified = load_modified_detail_data(DATA_DIR)

    print("Step 4: Loading resolver path data...")
    df_path = load_resolver_path_data(DATA_DIR)

    if not df_cache.empty:
        print(f"Loaded cache data for {len(df_cache)} transactions.")
        print(f"Loaded path data for {len(df_path)} response records.")
        print("Step 5: Generating cache visualizations...")

        # Original visualizations
        viz_1_cache_churn_stack(df_cache, OUTPUT_DIR)
        viz_2_net_growth_and_modify_ratio(df_cache, OUTPUT_DIR)
        viz_3_added_rtype_distribution(df_cache, OUTPUT_DIR)
        viz_4_modified_rtype_distribution(df_cache, OUTPUT_DIR)
        viz_5_max_ttl_observed(df_cache, OUTPUT_DIR)

        # Policy related visualizations
        viz_6_negative_cache_comparison(df_policy, OUTPUT_DIR)
        viz_7_trigger_vs_cached_records(df_policy, OUTPUT_DIR)
        viz_8_modification_type_breakdown(df_policy, OUTPUT_DIR)
        viz_9_ttl_refresh_deviation(df_modified, OUTPUT_DIR)
        viz_10_resolver_comparison_summary(df_policy, OUTPUT_DIR)

        # Resolver Path related visualizations (newly added)
        viz_11_response_record_cache_rate(df_path, OUTPUT_DIR)
        viz_12_aa_ad_cache_rate(df_path, OUTPUT_DIR)
        viz_13_rtype_cache_rate_by_section(df_path, OUTPUT_DIR)
        viz_14_resolver_policy_heatmap(df_path, OUTPUT_DIR)
        viz_15_aa_ad_response_stats(df_path, OUTPUT_DIR)

        print(f"All cache visualizations completed! Check {OUTPUT_DIR}")
    else:
        print("No valid cache data found.")