# /etc/deadwood/dwood3rc
# This is a simple Deadwood configuration file
chroot_dir = "/usr/local/etc"

# 1. Listen on 0.0.0.0
# This makes Deadwood listen on all IPv4 network interfaces on the machine.
bind_address = "0.0.0.0"

# 2. Allow anyone to access (open resolver)
# "0.0.0.0/0" is a special CIDR address that represents "all IPv4 addresses".
# !!! Please make sure to read the security warning below !!!
recursive_acl = "0.0.0.0/0"

# 3. Specify your own root hints file
# Make sure this path is the correct absolute path.
root_servers = {}
root_servers["."] = "{ROOT_HINT}"
upstream_servers = {}

filter_rfc1918 = 0
