server:
    num-threads: 8
    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    # Other settings
    # Allow access only from the local network
    access-control: 10.0.0.0/8 allow
    # Adjust the verbosity of the log
    verbosity: 4
    qname-minimisation: yes
    harden-glue: no                 # (default yes) Do not verify the correctness of glue records
    harden-dnssec-stripped: no      # (default yes) Do not check whether DNSSEC data has been maliciously stripped
    harden-below-nxdomain: no       # (default yes) Do not defend against NXDOMAIN attacks
    harden-referral-path: no        # (default no, but better to explicitly disable) Do not check the legitimacy of the query path
    harden-algo-downgrade: no       # (default no) Allow algorithm downgrade attacks
    # infra-cache-numhosts: 0
    infra-host-ttl: 0
    infra-keep-probing: yes

    auto-trust-anchor-file: ""  # Clear the auto trust anchor
    trust-anchor-file: ""       # Clear the manual trust anchor
    val-clean-additional: no        

    unwanted-reply-threshold: 0     # Do not reject any "unwanted" responses
    use-syslog: no
    target-fetch-policy: "-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1"